apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
  labels:
    app.kubernetes.io/part-of: augur
type: kubernetes.io/dockerconfigjson
# Provide either 'stringData' (raw json) or 'data' (base64-encoded json).
# Replace <QUAY_AUTH_BASE64> with base64 encoded 'username:password' or 'robot-username:token'.
# Alternatively, create directly with the oc CLI:
#   oc create secret docker-registry quay-secret \
#     --docker-server=quay.io \
#     --docker-username="<QUAY_USERNAME>" \
#     --docker-password="<QUAY_PASSWORD_OR_TOKEN>" \
#     --docker-email="<OPTIONAL_EMAIL>"
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "quay.io": {
          "auth": "<BASE64_ENCODED_USER_AND_TOKEN_OR_PASSWORD>",
          "email": ""
        }
      }
    }
