[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agentmesh-code-understanding"
version = "0.1.0"
dependencies = [
    "litellm",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["scripts*", "notebooks*", "compiled_pipelines*", "tests*"]
namespaces = true

[tool.setuptools.package-data]
"*" = [
    "*.sh",
    "*.json",
    "*.jsonl",
    "*.yaml",
    "*.yaml.in",
    "*.toml",
    "*.txt",
    "*.md",
    "*.csv",
    "*.tsv",
    "*.xml",
    "*.jinja",
    "*.jinja2",
    "*.j2",
    "*.in",
    "*.html",
    "*.parquet",
    "**/*.sh",
    "**/*.json",
    "**/*.jsonl",
    "**/*.yaml",
    "**/*.yaml.in",
    "**/*.toml",
    "**/*.txt",
    "**/*.md",
    "**/*.csv",
    "**/*.tsv",
    "**/*.xml",
    "**/*.jinja",
    "**/*.jinja2",
    "**/*.j2",
    "**/*.in",
    "**/*.html",
    "**/*.parquet",
]

