[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agentmesh-code-understanding"
version = "0.1.0"
dependencies = []

[tool.setuptools]
packages = ["pipelines", "pipelines.base", "pipelines.kubeflow", "utils", "loaders", "flows", "config", "assets"]

[tool.setuptools.package-data]
"*" = [
    "*.sh",
    "*.json",
    "*.jsonl",
    "*.yaml",
    "*.yaml.in",
    "*.toml",
    "*.txt",
    "*.md",
    "*.csv",
    "*.tsv",
    "*.xml",
    "*.jinja",
    "*.jinja2",
    "*.j2",
    "*.in",
    "*.html",
    "*.parquet",
]
