ARG BASE_IMAGE=registry.access.redhat.com/ubi9/python-311
FROM ${BASE_IMAGE}

USER 1001
WORKDIR /opt/app-root/src

ENV PIP_CACHE_DIR=/opt/app-root/src/.cache/pip

COPY --chown=1001:0 resources/images/pipeline-tools/requirements.txt ./requirements.txt

RUN --mount=type=cache,target=/opt/app-root/src/.cache/pip,uid=1001,gid=0 \
	pip install --upgrade pip \
	&& pip install -r requirements.txt

COPY --chown=1001:0 workflows/examples/code_understanding ./workflows/examples/code_understanding

RUN --mount=type=cache,target=/opt/app-root/src/.cache/pip,uid=1001,gid=0 \
	pip install ./workflows/examples/code_understanding
