ARG BASE_IMAGE=quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.11-2024b-20250904-858c895
FROM ${BASE_IMAGE}

USER 1001
WORKDIR /opt/app-root/src

# Tiktoken offline cache setup
ENV TIKTOKEN_CACHE_DIR=/opt/app-root/src/tiktoken_cache
RUN mkdir -p /opt/app-root/src/tiktoken_cache
COPY --chown=1001:0 cl100k_base.tiktoken /opt/app-root/src/tiktoken_cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4

COPY --chown=1001:0 resources/images/data-analysis/requirements.txt ./requirements.txt
COPY --chown=1001:0 workflows/examples/code_understanding ./workflows/examples/code_understanding

RUN pip install --no-cache-dir --upgrade pip \
	&& pip install --no-cache-dir -r requirements.txt \
	&& pip install --no-cache-dir ./workflows/examples/code_understanding
