ARG BASE_IMAGE=quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.11-2024b-20250904-858c895
FROM ${BASE_IMAGE}

USER 1001

# Tiktoken offline cache setup
ENV TIKTOKEN_CACHE_DIR=/opt/app-root/src/tiktoken_cache
RUN mkdir -p /opt/app-root/src/tiktoken_cache
COPY --chown=1001:0 cl100k_base.tiktoken /opt/app-root/src/tiktoken_cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4

ENV PIP_CACHE_DIR=/opt/app-root/src/.cache/pip

COPY requirements.txt ./requirements.txt

RUN pip install --upgrade pip \
	&& pip install -r requirements.txt
